service: aws-serverless-go

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
          Resource:
            - "" 

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  inserirProduto:
    handler: bin/InserirProduto
    events:
      - httpApi:
          path: /produtos
          method: post

resources:
  Resources:
    Produtos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Produtos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1